### ISSUE TITLE
When a job timeout, krawler hangs with the following error: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by robinbourianes-frizko** [kalisio/krawler#135]
Running hubeau krawler job with `DEBUG=*`, the last log entry before the crash is the following:

> 
>   krawler:jobs 1970 tasks ran from start in 1800106.770962 ms +0ms
>   @feathersjs/errors Timeout(408): Job timeout reached +0ms
>   @feathersjs/errors {} +1ms
>   krawler:jobs Some tasks failed Timeout: Job timeout reached
>     at new Timeout (/hdd/robin/Taff/kalisio/krawler/node_modules/@feathersjs/errors/lib/index.js:135:17)
>     at Object.<anonymous> (/hdd/robin/Taff/kalisio/krawler/lib/jobs/jobs.async.js:81:68)
>     at Generator.next (<anonymous>)
>     at step (/hdd/robin/Taff/kalisio/krawler/lib/jobs/jobs.async.js:112:191)
>     at /hdd/robin/Taff/kalisio/krawler/lib/jobs/jobs.async.js:112:361
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
>   type: 'FeathersError',
>   code: 408,
>   className: 'timeout',
>   data: undefined,
>   errors: {}
> } +1ms

Without DEBUG=* the only line we get is `Cannot read property 'type' of undefined` which is printed from here: https://github.com/kalisio/krawler/blob/f86541ae469f65832840bf7abb42a1d32912d596/src/cli.js#L148

**Comment by robinbourianes-frizko** [comment]
The `type` property the code tries to read is from [here](https://github.com/feathersjs-ecosystem/feathers-hooks-common/blob/v3.10.0/src/services/get-items.js#L3)
Somehow throwing the timeout error from [here](https://github.com/kalisio/krawler/blob/7a667838839a2b07a0769715b4ba185407f7d435/src/jobs/jobs.async.js#L74) mess up stuff in feathers.
Feathers god help requested ! @claustres

**Comment by claustres** [comment]
If the error hooks are removed from the job the error goes away, it is probably related to the fact some of our internal hooks do not correctly manage the error hook case.
