### ISSUE TITLE
Job hangs after mongo connection failure

### ISSUE THREAD

**Issue by claustres** [kalisio/krawler#47]
### Steps to reproduce

Run a non fault-tolerant job with a connectMongo hook without the DB available.

### Expected behavior

The job stops with error

### Actual behavior

The job hangs with the following message `Cannot read property 'hasOwnProperty' of undefined`

### System configuration

Tell us about the applicable parts of your setup.

**NodeJS version**: 8

**Operating System**: windows

**Comment by cnouguier** [comment]
I had something similar but the DB is reached as the job is able to create the collection where to write the data. Need to investigate.

**Comment by claustres** [comment]
Related to the fact error hooks does not have the same structure than "standard" ones so that the match filtering raised an exception.
