### ISSUE TITLE
Node hangs when a job with a timeout is finished

### ISSUE THREAD

**Issue by robinbourianes-frizko** [kalisio/krawler#92]
For example in this job: https://github.com/kalisio/c3x-arpege/blob/ef7bd729dcbcf14d435313904a683dd735603150/jobfile-arpege-0.1.js

if the `timeout` option is defined, then node will hang when the job fails (which is sometimes expected). Using [why-is-node-running](https://www.npmjs.com/package/why-is-node-running) to see why it hangs, the following line shows up :

`krawler/lib/jobs/jobs.async.js:15  - if (options.timeout) setTimeout(function () {`

When the timeout is not defined and the job fails, node ends correctly.

**Comment by claustres** [comment]
The timeout [here](https://github.com/kalisio/krawler/blob/master/src/jobs/jobs.async.js#L13) makes node waits until it is finished before exiting.
